version: '3.8'

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ~/projects:/var/www
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    container_name: laravel-php
    volumes:
      - ~/projects:/var/www
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

